apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv-cql-0
  labels:
    cassandra-node: "0"  # Added label for explicit matching
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-master
  hostPath:
#    path: "/mnt/ecs_pool_0_0153/kubernetes-namespaces/deployments/cassandra/cassandra-manual/cassandra-data1"
    path: "/opt/cassandra-data/cassandra-data-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv-cql-1
  labels:
    cassandra-node: "1"  # Added label for explicit matching
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1
  hostPath:
    path: "/opt/cassandra-data/cassandra-data-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv-cql-2
  labels:
    cassandra-node: "2"  # Added label for explicit matching
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker1
  hostPath:
    path: "/opt/cassandra-data/cassandra-data-2"
